# varibale level
# cli level
#task level
# role level
#play level

- name: Variable demo
  hosts: localhost
  connection: local
  vars: #play level
    a: 100
    b: 200
  tasks: #task level
    - name: Print variable
      ansible.builtin.debug:
        msg: a - {{a}}

    - name: Print variable
      vars:
        a: 200
      ansible.builtin.debug:
        msg: a - {{a}}